"""Helpers for writing processed NetCDF files with clear provenance."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import xarray as xr

from data_pipeline.common.logging_setup import get_logger

log = get_logger(__name__)

DEMO_GLOBAL_ATTRS: dict[str, str] = {
    "classification": "synthetic_demo",
    "source_name": "synthetic-demo-generator",
    "notice": (
        "SYNTHETIC DEMO DATA - generated by create_demo_data.py. "
        "Not real measurements; never use for operational navigation decisions."
    ),
    "generated_at_utc": "",
}

REAL_GLOBAL_ATTRS: dict[str, str] = {
    "classification": "real_observation",
    "notice": "Source-provided data; refer to the provider license and citation requirements.",
    "generated_at_utc": "",
}


def stamp_attrs(attrs: dict[str, str]) -> dict[str, str]:
    attrs = dict(attrs)
    attrs["generated_at_utc"] = datetime.now(timezone.utc).isoformat()
    return attrs


def write_netcdf(
    ds: xr.Dataset,
    path: Path | str,
    *,
    encoding: dict[str, Any] | None = None,
) -> Path:
    """Write an xarray Dataset to NetCDF, creating parent dirs.

    Configures lossless integer/time encodings to keep files small and
    time coordinates timezone-safe.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    enc = dict(encoding or {})
    if "time" in ds.coords and "time" not in enc:
        enc["time"] = {
            "dtype": "int64",
            "units": "microseconds since 1970-01-01 00:00:00",
            "calendar": "proleptic_gregorian",
        }

    ds.to_netcdf(path, encoding=enc)
    log.info("Wrote NetCDF: %s (%s)", path, _human_size(path.stat().st_size))
    return path


def _human_size(size: int) -> str:
    for unit in ("B", "KiB", "MiB", "GiB"):
        if size < 1024:
            return f"{size} {unit}"
        size /= 1024
    return f"{size:.1f} GiB"